import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
CubeMX_Config/Src/stm32f4xx_hal_msp.c
CubeMX_Config/Src/main.c
''')

if GetDepend(['BSP_USING_QSPI_FLASH']):
    src += ['ports/drv_qspi_flash.c']

if GetDepend(['PKG_USING_FAL']):
    src += ['ports/qspi_mnt.c']
    
if GetDepend(['BSP_USING_LCD_OTM8009A']):
    src += ['ports/drv_otm8009a.c']
    
if GetDepend(['BSP_USING_TOUCH']):
    src += Glob('ports/touch/*.c')
    
if GetDepend(['BSP_USING_SDCARD']):
    src += ['ports/drv_sdcard.c']
    
if GetDepend(['BSP_USING_QSPI']):
    src += ['ports/drv_qspi_flash.c']

path =  [cwd]
path += [cwd + '/CubeMX_Config/Inc']
path += [cwd + '/ports']

startup_path_prefix = SDK_LIB
custom_startup_path_prefix = cwd
custom_startup_path_prefix += '/CubeMX_Config'
# GCC,IAR path may be wrong,please fix it with your actual path
if rtconfig.CROSS_TOOL == 'gcc':
    src += [custom_startup_path_prefix + '/GCC/startup_stm32f429xx.s']
elif rtconfig.CROSS_TOOL == 'keil':
    src += [custom_startup_path_prefix + '/MDK-ARM/startup_stm32f429xx.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src += [custom_startup_path_prefix + '/IAR/startup_stm32f429xx.s']

# STM32F405xx) || STM32F415xx) || STM32F407xx) || STM32F417xx)
# STM32F427xx) || STM32F437xx) || STM32F429xx) || STM32F439xx)
# STM32F401xC) || STM32F401xE) || STM32F410Tx) || STM32F410Cx)
# STM32F410Rx) || STM32F411xE) || STM32F446xx) || STM32F469xx)
# STM32F479xx) || STM32F412Cx) || STM32F412Rx) || STM32F412Vx)
# STM32F412Zx) || STM32F413xx) || STM32F423xx)
# You can select chips from the list above
CPPDEFINES = ['STM32F429xx']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
